# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65e942607f83e13c26c8f50c6b6d03a91a003e969306a7ce73b819cf4b11fe9c2957ef13461ba481daccd30a622a7970a420ab118aaf878e09bfc7ffb38ae2f7

test:
  secret_key_base: cbe60961acbf2215822e04008de65fadf32c830c29841ac53ba7da60db3efa80bd86debcbf53b5367d4a822be113484a7e769cfea43ce165fccd01aa372e618b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
